### ISSUE TITLE
DAFlow 코드 모듈화 및 깔끔하게 수정

### ISSUE THREAD

**Issue by Ui-Seok** [boostcampaitech4lv23cv2/final-project-level3-cv-12#12]
### ISSUE
 * Type: feat, fix
 * Detail: DressCode dataset 사용 가능하게 코드 작성, 안쓰이는 코드 삭제 및 코드 가독성 증가
### TODO
- [x]  DressCodeDataset class 코드 생성
- [x] Train, Test code 합치기 → 따로 분리해서 사용
- [x]  불필요한 코드 삭제 및 주석 처리
- [x] WandB 연동하기
