### ISSUE TITLE
Streamlit - FastAPI 테스트 코드

### ISSUE THREAD

**Issue by Ui-Seok** [boostcampaitech4lv23cv2/final-project-level3-cv-12#20]
### ISSUE
 * Type: feat
 * Detail: 강의 과제로 streamlit과 fastAPI를 활용한 Virtual Try-On 테스트 코드
### TODO
- [x] README.md 파일 작성하기
- [ ] back에서 Tensor를 byte로 변환하여 front로 전달하는 코드 수정
- [ ] Path Parameter 주소 수정(order에서 다른 것으로)

**Comment by Ui-Seok** [comment]
FastAPI는 사용하지않고 BentoML을 사용하기로 결정
