### ISSUE TITLE
학습에 필요한 agnositc image 구하기

### ISSUE THREAD

**Issue by Ui-Seok** [boostcampaitech4lv23cv2/final-project-level3-cv-12#3]
### ISSUE
 * Type: feat
 * Detail: model input으로 agnostic image가 들어가는데 이를 만들어주기 위한 코드
### TODO
- [X]  Version 1.0: human parsing map을 기준으로 코드 작성
- [X]  Version 2.0: skeleton json file을 기준으로 부위별로(상체, 하체, 전신) 코드 작성
- [x]  Version 3.0: human parsing map + skeleton json file을 모두 고려한 코드 작성
### PROBLEM & SOLUTION
- Version 1.0
> HR-VITON에서는 목 부분과 얼굴 부분에 대한 mask 정보가 분리되어 있어 목 부분만 제거를 하였는데 dress_code의 데이터는 목과 얼굴이 하나의 mask 정보로 되어있어 현재는 불가피하게 목과 얼굴이 전부 날라감
> Sol: skeleton 정보를 활용하여 masking 처리
- Version 2.0
> 손 부분이나 머리카락, 머리, 허리 같은 살려야 하는 부분을 확인하지 못하고 다 masking 처리하는 문제점이 있음
> Sol: human parsing 정보를 확인하여 skeleton 정보와 융합
