### ISSUE TITLE
서브 데이터셋 분리 코드 작성

### ISSUE THREAD

**Issue by wowns1484** [boostcampaitech4lv23cv2/final-project-level3-cv-12#5]
### ISSUE
 * Type: feature
 * Detail: 전체 데이터셋 용량이 너무 큰 문제로 서브 데이터셋으로 분리하는 코드 작성
 
### TODO
- [x] split_dataset.py 구현
- [x] argument로 mode를 copy 사용 시 shutil.copy2 활용해 output_dir로 복사 (원본 유지) 
- [x] argument로 mode를 move 사용 시  shutil.move 활용해 output_dir로 이동 (원본 이동)
