### ISSUE TITLE
오류 수정 및 부하 테스트 추가

### ISSUE THREAD

**Issue by wowns1484** [boostcampaitech4lv23cv2/final-project-level3-cv-12#51]
### ISSUE
 * Type: `feature`, `fix`, 'refactor'
 * Detail: 
 * 1. back-end 서버에 부하 테스트 가능한 코드 추가
 * 2. sample 이미지들이 모두 back-end 경로에서 접근하는 부분 수정
 * 3. Makefile 활용해 모델 체크포인트 다운로드 시 옵션 이슈로 인한 경로 불일치 문제 발생

### TODO
- [x]  부하 테스트 수행
- [x]  sample 이미지 경로 조정
- [x]  체크포인트 다운로드 오류 수정
